name: Build YTKP deb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev xz-utils

      - name: Clone and build (max compression)
        run: |
          git clone --quiet --depth=1 https://git.0x0.st/mrdrvt99/YTKP.git
          cd YTKP
          chmod -R 755 .

          # Maximum compression with xz
          dpkg-deb --root-owner-group -Zxz -z9 --build . ../ytkplus.deb

      - name: Show size
        run: ls -lh ytkplus.deb

      - name: Upload the .deb
        uses: actions/upload-artifact@v7
        with:
          name: ytkplus-deb
          path: ytkplus.deb
